prior: [0.90, 0.10]
num_epochs: 500
batch_size: 8 # This should be rather small to be memory efficient
learning_rate: 0.0005
evaluate_every_k_epochs: 10
alpha: 0.5 # weight for nll loss
beta: 1.0 # weight for kl loss

training_dataset_path: results/nri_dataset/train_node_features_l2rpn_case14_sandbox_2025-10-21_00:43_no_forecast.npy
testing_dataset_path: results/nri_dataset/test_node_features_l2rpn_case14_sandbox_2025-10-21_00:43_no_forecast.npy
features_to_predict:
    - active_power
    - reactive_power
    - voltage
    - voltage_angle
    - current
    - rho
