sb3:
    _target_: stable_baselines3.dqn.dqn.DQN
    verbose: 1
    train_freq: 16
    gradient_steps: 8
    gamma: 0.99
    exploration_fraction: 0.2
    exploration_final_eps: 0.07
    target_update_interval: 600
    learning_starts: 1000
    buffer_size: 10000
    batch_size: 128
    learning_rate: 4e-3

name: dqn
