net_arch: [ 256, 256, 256 ]
prior_for_graph_edges_existing: 0.9
temperature: 0.2
name_suffix: ~
use_graphormer: true
features_extractor_kwargs:
    hidden_dim: 64
    out_dim: 64
    num_edge_types: 2
    num_layers: 2
    dropout_prob: 0
    max_degree: 7 # todo change if bigger envs are considered
    max_path_distance: 9 # todo change if bigger envs are considered