sb3:
    _target_: src.ra_agents.dqn.SoftmaxDQN.SoftmaxDQN
    verbose: 1
    train_freq: 16
    gradient_steps: 8
    gamma: 0.99
    tau_start: 0.5
    tau_end: 0.0000001
    exploration_fraction: 0.2
    exploration_final_eps: 0.07
    target_update_interval: 600
    learning_starts: 5000
    buffer_size: 100000
    batch_size: 32
    learning_rate: 4e-3
    policy_kwargs:
        net_arch: ${rl.model.net_arch}
        features_extractor_kwargs:
            hidden_dim: ${rl.model.features_extractor_kwargs.hidden_dim}
            out_dim: ${rl.model.features_extractor_kwargs.out_dim}
            num_edge_types: ${rl.model.features_extractor_kwargs.num_edge_types}
            num_layers: ${rl.model.features_extractor_kwargs.num_layers}
            dropout_prob: ${rl.model.features_extractor_kwargs.dropout_prob}

exploration: "Softmax"

loss:
    alpha: 0.02
    beta: 1.0

topology_policy:
    _target_: baselines.topo_policies_sb3.TopoPolicyStableDQN
