prior: [0.9, 0.1]
num_epochs: 100
batch_size: 8 # This should be rather small to be memory efficient
learning_rate: 0.0005
evaluate_every_k_epochs: 10
training_dataset_path: data/nri_dataset/train_node_features_l2rpn_case14_sandbox_2025-10-17_18:59_.npy
testing_dataset_path: data/nri_dataset/test_node_features_l2rpn_case14_sandbox_2025-10-17_18:59_.npy