defaults:
    -   env: case14
    -   baseline: gnn_dqn
    -   nri: with_forecast_and_bus_indices
    -   ra_dqn: default
    - _self_

hydra:
    run:
        dir: data/output/${now:%Y-%m-%d_%H-%M-%S}