defaults:
    -   env: case14
    -   nri: default
    -   rl: default
    -   optuna: default
    - _self_

experiment_name: learning_progress
timeout: ~

hydra:
    run:
        dir: data/experiments/${experiment_name}/hydra/${now:%Y-%m-%d_%H-%M-%S}
