_target_: src.common.observation_space.BusConnectivityGraphObsSpace
normalization_boundaries:
    active_power_forecast: [-122.4, 116,666]
    active_power: [-122.4, 116,666]
    reactive_power_forecast: [-85.7, 107.228]
    reactive_power: [-85.7, 107.228]
    voltage: [-142.1, 142.1]
    voltage_angle: [-14.212, 1.246]
    current: [0, 1512]
    rho: [0, 1]