timesteps: 300_000
batch_size: 128
learning_rate: 0.004
gamma: 0.99
buffer_size: 10000
train_freq: 16
gradient_steps: 8
exploration_fraction: 0.2
exploration_final_eps: 0.07
target_update_interval: 600
learning_starts: 1000
