sb3:
    _target_: ra_agents/ppo/RAPPO/RAPPO
    verbose: 1
    learning_rate: 0.0001
    n_steps: 1024  # number of steps to run per update
    batch_size: 256 # batch size when optimizing the surrogate loss
    n_epochs: 5   # number of epochs when optimizing the surrogate loss
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.3
    clip_range_vf: ~
    normalize_advantage: true
    ent_coef: 0.0
    vf_coef: 0.5
    kl_coef: 1.0
    max_grad_norm: 0.5
    use_sde: false
    sde_sample_freq: -1

    policy_kwargs:
        net_arch: ${rl.model.net_arch}
        features_extractor_kwargs:
            hidden_dim: ${rl.model.features_extractor_kwargs.hidden_dim}
            out_dim: ${rl.model.features_extractor_kwargs.out_dim}
            num_edge_types: ${rl.model.features_extractor_kwargs.num_edge_types}
            num_layers: ${rl.model.features_extractor_kwargs.num_layers}
            dropout_prob: ${rl.model.features_extractor_kwargs.dropout_prob}

topology_policy:
    _target_: baselines.topo_policies_sb3.TopoPolicyStablePPO
