timesteps: 250_000
log_interval: 100
curriculum_level_config:
    active: true
    start_level: 0
    level1_at_fraction: 0.2        # 1/5 of total training time
    level2_at_fraction: 0.4666667  # 7/15 of total training time
pretrain_encoder:
    ds_size: 1000
    test_ds_size: 100
    num_epochs: 100
    batch_size: 50
    learning_rate: 0.005
    evaluate_every_k_epochs: 10
