sb3:
    _target_: nri/agent/RADQN
    verbose: 1
    train_freq: 16
    gradient_steps: 8
    gamma: 0.99
    exploration_fraction: 0.2
    exploration_final_eps: 0.07
    target_update_interval: 600
    learning_starts: 1000
    buffer_size: 10000
    batch_size: 32
    learning_rate: 4e-3
    policy_kwargs:
        net_arch: [ 100 ]
        features_extractor_kwargs:
            hidden_dim: 32
            out_dim: 32
            num_edge_types: 2
            dropout_prob: 0.1

loss:
    alpha: 1.0
    beta: 1.0
    prior_for_graph_edges: [0.9, 0.1]
    prior_for_non_graph_edges: [0.1, 0.9]

topology_policy:
    _target_: baselines.topo_policies_sb3.TopoPolicyStableDQN
