sb3:
    _target_: nri/agent/RADQN
    verbose: 1
    train_freq: 16
    gradient_steps: 8
    gamma: 0.99
    exploration_fraction: 0.2
    exploration_final_eps: 0.07
    target_update_interval: 600
    learning_starts: 1000
    buffer_size: 10000
    batch_size: 32
    learning_rate: 4e-3
    policy_kwargs:
        net_arch: [ 100 ]
        features_extractor_kwargs:
            hidden_dim: 32
            out_dim: 32
            num_edge_types: 2
            num_layers: 3
            dropout_prob: 0.1

ray:
    exploration_fraction: ${ra_dqn.model.sb3.exploration_fraction}
    exploration_final_eps: ${ra_dqn.model.sb3.exploration_final_eps}
    target_network_update_freq: ${ra_dqn.model.sb3.target_update_interval}
    num_steps_sampled_before_learning_starts: ${ra_dqn.model.sb3.learning_starts}
    lr: ${ra_dqn.model.sb3.learning_rate}
    double_q: true
    dueling: true
    train_batch_size_per_learner: ${ra_dqn.model.sb3.batch_size}
    replay_buffer_config:
        type: PrioritizedEpisodeReplayBuffer
        capacity: ${ra_dqn.model.sb3.buffer_size}
        alpha: 0.5,
        beta: 0.5,

loss:
    alpha: 0.1
    beta: 1.0
    prior_for_graph_edges: [0.9, 0.1]
    prior_for_non_graph_edges: [0.1, 0.9]

topology_policy:
    _target_: baselines.topo_policies_sb3.TopoPolicyStableDQN
