sb3:
    _target_: stable_baselines3.ppo.ppo.PPO
    verbose: 1
    learning_rate: 0.0001
    n_steps: 128
    batch_size: 32
    n_epochs: 30
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.3
    clip_range_vf: 100
    normalize_advantage: true
    ent_coef: 0.05
    vf_coef: 0.5
    max_grad_norm: 0.5

name: ppo
topology_policy:
    _target_: baselines.topo_policies_sb3.TopoPolicyStablePPO
