name: "l2rpn_case14_sandbox"
rule_config:
    activation_threshold: 0.95
    line_reco: true
    line_disc: false
    reset_topo: 0.9
    simulate: true

training_env:
    _target_: src.common.env.G2OpGymEnv
    env_name: "${env.name}_train"
    rule_config: ${env.rule_config}
